version: '2'

services:

  web:
    image: bved/php-apache:5.6
    depends_on:
      - opencart
      - mysql
    volumes:
      - www:/var/www/html
    ports:
        - "80:80"

  opencart:
    image: bved/opencart:<version>
    volumes:
          - www:/www
    tty: true

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: opencart
      MYSQL_ROOT_PASSWORD: opencart

volumes:
  www: