version: "3"

services:

  2.1.0.2:
    image: bved/opencart:2.1.0.2
    build: ./2.1.0.2/origin/

  2.1.0.2.qs:
      image: bved/opencart:2.1.0.2.qs
      build: ./2.1.0.2/qs/

  2.3.0.2:
    image: bved/opencart:2.3.0.2
    build: ./2.3.0.2/origin/

  2.3.0.2.qs:
      image: bved/opencart:2.3.0.2.qs
      build: ./2.3.0.2/qs/

  3.0.2.0:
    image: bved/opencart:3.0.2.0
    build: ./3.0.2.0/origin/

  3.0.2.0.qs:
      image: bved/opencart:3.0.2.0.qs
      build: ./3.0.2.0/qs/